services:
  - type: web
    name: quotly-bot
    env: python
    plan: free
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
    startCommand: python bot.py
